#!/bin/bash
tput setaf 2
tput bold
echo ""
echo "Self Extracting Installer"
echo ""
tput sgr0
ARCHIVE=`awk '/^__ARCHIVE_BELOW__/ {print NR + 1; exit 0; }' $0`

tail -n+$ARCHIVE $0 | tar xzv

./install

exit 0

__ARCHIVE_BELOW__
